### ISSUE TITLE
Route model binding does not work

### ISSUE THREAD

**Issue by Dirk94** [mohammedmanssour/form-request-tester#1]
First of all, love the package. Unfortunately, the route model binding does not seem to work.

**Steps to reproduce.**

The form request
```
class CreateResourceRequest extends FormRequest
{
    public function authorize()
    {
      $user = $this->route("user");
      var_dump($user);
      die();
    }
}
```

Create an explicit binding
```
Route::model('user', App\User::class);
```

Run the test
```
$user = $this->createUser(); // Create a random test user.
$this->formRequest(CreateResourceRequest::class, [], [
    'method' => 'POST',
    'route' => "/resources/{$user->id}/create"
]);
```

The output is the id of the user instead of the user model.
```
int 1
```

**Comment by mohammedmanssour** [comment]
Hi, sorry for the late response!

I'll be working to fix it as soon as possible

**Comment by mohammedmanssour** [comment]
fixed in https://github.com/mohammedmanssour/form-request-tester/pull/10
